//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naloga_6.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int EmsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        private int LetoRojstvaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Emso {
            get {
                return this.EmsoField;
            }
            set {
                if ((this.EmsoField.Equals(value) != true)) {
                    this.EmsoField = value;
                    this.RaisePropertyChanged("Emso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LetoRojstva {
            get {
                return this.LetoRojstvaField;
            }
            set {
                if ((this.LetoRojstvaField.Equals(value) != true)) {
                    this.LetoRojstvaField = value;
                    this.RaisePropertyChanged("LetoRojstva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Studentski_dom", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Studentski_dom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int Stevilka_DomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        private int Leto_NastankaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Stevilka_Doma {
            get {
                return this.Stevilka_DomaField;
            }
            set {
                if ((this.Stevilka_DomaField.Equals(value) != true)) {
                    this.Stevilka_DomaField = value;
                    this.RaisePropertyChanged("Stevilka_Doma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Leto_Nastanka {
            get {
                return this.Leto_NastankaField;
            }
            set {
                if ((this.Leto_NastankaField.Equals(value) != true)) {
                    this.Leto_NastankaField = value;
                    this.RaisePropertyChanged("Leto_Nastanka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentVDomu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StudentVDomu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private naloga_6.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private naloga_6.ServiceReference1.Studentski_dom DomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipField;
        
        private int Dolzina_bivanjaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public naloga_6.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public naloga_6.ServiceReference1.Studentski_dom Dom {
            get {
                return this.DomField;
            }
            set {
                if ((object.ReferenceEquals(this.DomField, value) != true)) {
                    this.DomField = value;
                    this.RaisePropertyChanged("Dom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tip {
            get {
                return this.TipField;
            }
            set {
                if ((object.ReferenceEquals(this.TipField, value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Dolzina_bivanja {
            get {
                return this.Dolzina_bivanjaField;
            }
            set {
                if ((this.Dolzina_bivanjaField.Equals(value) != true)) {
                    this.Dolzina_bivanjaField = value;
                    this.RaisePropertyChanged("Dolzina_bivanja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StoritveSoap")]
    public interface StoritveSoap {
        
        // CODEGEN: Generating message contract since element name uporabniško_ime from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vpis", ReplyAction="*")]
        naloga_6.ServiceReference1.vpisResponse vpis(naloga_6.ServiceReference1.vpisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vpis", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.vpisResponse> vpisAsync(naloga_6.ServiceReference1.vpisRequest request);
        
        // CODEGEN: Generating message contract since element name PridobiVseStudenteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PridobiVseStudente", ReplyAction="*")]
        naloga_6.ServiceReference1.PridobiVseStudenteResponse PridobiVseStudente(naloga_6.ServiceReference1.PridobiVseStudenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PridobiVseStudente", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseStudenteResponse> PridobiVseStudenteAsync(naloga_6.ServiceReference1.PridobiVseStudenteRequest request);
        
        // CODEGEN: Generating message contract since element name PridobiVseDomoveResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PridobiVseDomove", ReplyAction="*")]
        naloga_6.ServiceReference1.PridobiVseDomoveResponse PridobiVseDomove(naloga_6.ServiceReference1.PridobiVseDomoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PridobiVseDomove", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseDomoveResponse> PridobiVseDomoveAsync(naloga_6.ServiceReference1.PridobiVseDomoveRequest request);
        
        // CODEGEN: Generating message contract since element name PridobiVseStudenteVDomuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PridobiVseStudenteVDomu", ReplyAction="*")]
        naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponse PridobiVseStudenteVDomu(naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PridobiVseStudenteVDomu", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponse> PridobiVseStudenteVDomuAsync(naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest request);
        
        // CODEGEN: Generating message contract since element name VrniStudentaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VrniStudenta", ReplyAction="*")]
        naloga_6.ServiceReference1.VrniStudentaResponse VrniStudenta(naloga_6.ServiceReference1.VrniStudentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VrniStudenta", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.VrniStudentaResponse> VrniStudentaAsync(naloga_6.ServiceReference1.VrniStudentaRequest request);
        
        // CODEGEN: Generating message contract since element name VrniDomResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VrniDom", ReplyAction="*")]
        naloga_6.ServiceReference1.VrniDomResponse VrniDom(naloga_6.ServiceReference1.VrniDomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VrniDom", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.VrniDomResponse> VrniDomAsync(naloga_6.ServiceReference1.VrniDomRequest request);
        
        // CODEGEN: Generating message contract since element name StudentVDomusResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StudentVDomus", ReplyAction="*")]
        naloga_6.ServiceReference1.StudentVDomusResponse StudentVDomus(naloga_6.ServiceReference1.StudentVDomusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StudentVDomus", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.StudentVDomusResponse> StudentVDomusAsync(naloga_6.ServiceReference1.StudentVDomusRequest request);
        
        // CODEGEN: Generating message contract since element name IzpisNajstarejsegaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IzpisNajstarejsega", ReplyAction="*")]
        naloga_6.ServiceReference1.IzpisNajstarejsegaResponse IzpisNajstarejsega(naloga_6.ServiceReference1.IzpisNajstarejsegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IzpisNajstarejsega", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.IzpisNajstarejsegaResponse> IzpisNajstarejsegaAsync(naloga_6.ServiceReference1.IzpisNajstarejsegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IzpisPovprecneStarosti", ReplyAction="*")]
        double IzpisPovprecneStarosti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IzpisPovprecneStarosti", ReplyAction="*")]
        System.Threading.Tasks.Task<double> IzpisPovprecneStarostiAsync();
        
        // CODEGEN: Generating message contract since element name student from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DodajStudenta", ReplyAction="*")]
        naloga_6.ServiceReference1.DodajStudentaResponse DodajStudenta(naloga_6.ServiceReference1.DodajStudentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DodajStudenta", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentaResponse> DodajStudentaAsync(naloga_6.ServiceReference1.DodajStudentaRequest request);
        
        // CODEGEN: Generating message contract since element name dom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DodajStudentskiDom", ReplyAction="*")]
        naloga_6.ServiceReference1.DodajStudentskiDomResponse DodajStudentskiDom(naloga_6.ServiceReference1.DodajStudentskiDomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DodajStudentskiDom", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentskiDomResponse> DodajStudentskiDomAsync(naloga_6.ServiceReference1.DodajStudentskiDomRequest request);
        
        // CODEGEN: Generating message contract since element name student from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DodajStudentaVDomu", ReplyAction="*")]
        naloga_6.ServiceReference1.DodajStudentaVDomuResponse DodajStudentaVDomu(naloga_6.ServiceReference1.DodajStudentaVDomuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DodajStudentaVDomu", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentaVDomuResponse> DodajStudentaVDomuAsync(naloga_6.ServiceReference1.DodajStudentaVDomuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniStudenta", ReplyAction="*")]
        bool OdstraniStudenta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniStudenta", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> OdstraniStudentaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniDom", ReplyAction="*")]
        bool OdstraniDom(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniDom", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> OdstraniDomAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniStudentaizDomov", ReplyAction="*")]
        bool OdstraniStudentaizDomov(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniStudentaizDomov", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> OdstraniStudentaizDomovAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniDomIzStudentVDomu", ReplyAction="*")]
        bool OdstraniDomIzStudentVDomu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdstraniDomIzStudentVDomu", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> OdstraniDomIzStudentVDomuAsync(int id);
        
        // CODEGEN: Generating message contract since element name Ime from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrediStudenta", ReplyAction="*")]
        naloga_6.ServiceReference1.UrediStudentaResponse UrediStudenta(naloga_6.ServiceReference1.UrediStudentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrediStudenta", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.UrediStudentaResponse> UrediStudentaAsync(naloga_6.ServiceReference1.UrediStudentaRequest request);
        
        // CODEGEN: Generating message contract since element name ime from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrediDom", ReplyAction="*")]
        naloga_6.ServiceReference1.UrediDomResponse UrediDom(naloga_6.ServiceReference1.UrediDomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrediDom", ReplyAction="*")]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.UrediDomResponse> UrediDomAsync(naloga_6.ServiceReference1.UrediDomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vpisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vpis", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.vpisRequestBody Body;
        
        public vpisRequest() {
        }
        
        public vpisRequest(naloga_6.ServiceReference1.vpisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vpisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uporabniško_ime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string geslo;
        
        public vpisRequestBody() {
        }
        
        public vpisRequestBody(string uporabniško_ime, string geslo) {
            this.uporabniško_ime = uporabniško_ime;
            this.geslo = geslo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vpisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vpisResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.vpisResponseBody Body;
        
        public vpisResponse() {
        }
        
        public vpisResponse(naloga_6.ServiceReference1.vpisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vpisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool vpisResult;
        
        public vpisResponseBody() {
        }
        
        public vpisResponseBody(bool vpisResult) {
            this.vpisResult = vpisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PridobiVseStudenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PridobiVseStudente", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.PridobiVseStudenteRequestBody Body;
        
        public PridobiVseStudenteRequest() {
        }
        
        public PridobiVseStudenteRequest(naloga_6.ServiceReference1.PridobiVseStudenteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PridobiVseStudenteRequestBody {
        
        public PridobiVseStudenteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PridobiVseStudenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PridobiVseStudenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.PridobiVseStudenteResponseBody Body;
        
        public PridobiVseStudenteResponse() {
        }
        
        public PridobiVseStudenteResponse(naloga_6.ServiceReference1.PridobiVseStudenteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PridobiVseStudenteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Student[] PridobiVseStudenteResult;
        
        public PridobiVseStudenteResponseBody() {
        }
        
        public PridobiVseStudenteResponseBody(naloga_6.ServiceReference1.Student[] PridobiVseStudenteResult) {
            this.PridobiVseStudenteResult = PridobiVseStudenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PridobiVseDomoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PridobiVseDomove", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.PridobiVseDomoveRequestBody Body;
        
        public PridobiVseDomoveRequest() {
        }
        
        public PridobiVseDomoveRequest(naloga_6.ServiceReference1.PridobiVseDomoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PridobiVseDomoveRequestBody {
        
        public PridobiVseDomoveRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PridobiVseDomoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PridobiVseDomoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.PridobiVseDomoveResponseBody Body;
        
        public PridobiVseDomoveResponse() {
        }
        
        public PridobiVseDomoveResponse(naloga_6.ServiceReference1.PridobiVseDomoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PridobiVseDomoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Studentski_dom[] PridobiVseDomoveResult;
        
        public PridobiVseDomoveResponseBody() {
        }
        
        public PridobiVseDomoveResponseBody(naloga_6.ServiceReference1.Studentski_dom[] PridobiVseDomoveResult) {
            this.PridobiVseDomoveResult = PridobiVseDomoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PridobiVseStudenteVDomuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PridobiVseStudenteVDomu", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequestBody Body;
        
        public PridobiVseStudenteVDomuRequest() {
        }
        
        public PridobiVseStudenteVDomuRequest(naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PridobiVseStudenteVDomuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int stevilka_doma;
        
        public PridobiVseStudenteVDomuRequestBody() {
        }
        
        public PridobiVseStudenteVDomuRequestBody(int stevilka_doma) {
            this.stevilka_doma = stevilka_doma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PridobiVseStudenteVDomuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PridobiVseStudenteVDomuResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponseBody Body;
        
        public PridobiVseStudenteVDomuResponse() {
        }
        
        public PridobiVseStudenteVDomuResponse(naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PridobiVseStudenteVDomuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Student[] PridobiVseStudenteVDomuResult;
        
        public PridobiVseStudenteVDomuResponseBody() {
        }
        
        public PridobiVseStudenteVDomuResponseBody(naloga_6.ServiceReference1.Student[] PridobiVseStudenteVDomuResult) {
            this.PridobiVseStudenteVDomuResult = PridobiVseStudenteVDomuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VrniStudentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VrniStudenta", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.VrniStudentaRequestBody Body;
        
        public VrniStudentaRequest() {
        }
        
        public VrniStudentaRequest(naloga_6.ServiceReference1.VrniStudentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VrniStudentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int emso;
        
        public VrniStudentaRequestBody() {
        }
        
        public VrniStudentaRequestBody(int emso) {
            this.emso = emso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VrniStudentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VrniStudentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.VrniStudentaResponseBody Body;
        
        public VrniStudentaResponse() {
        }
        
        public VrniStudentaResponse(naloga_6.ServiceReference1.VrniStudentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VrniStudentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Student VrniStudentaResult;
        
        public VrniStudentaResponseBody() {
        }
        
        public VrniStudentaResponseBody(naloga_6.ServiceReference1.Student VrniStudentaResult) {
            this.VrniStudentaResult = VrniStudentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VrniDomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VrniDom", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.VrniDomRequestBody Body;
        
        public VrniDomRequest() {
        }
        
        public VrniDomRequest(naloga_6.ServiceReference1.VrniDomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VrniDomRequestBody {
        
        public VrniDomRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VrniDomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VrniDomResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.VrniDomResponseBody Body;
        
        public VrniDomResponse() {
        }
        
        public VrniDomResponse(naloga_6.ServiceReference1.VrniDomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VrniDomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Studentski_dom VrniDomResult;
        
        public VrniDomResponseBody() {
        }
        
        public VrniDomResponseBody(naloga_6.ServiceReference1.Studentski_dom VrniDomResult) {
            this.VrniDomResult = VrniDomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentVDomusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentVDomus", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.StudentVDomusRequestBody Body;
        
        public StudentVDomusRequest() {
        }
        
        public StudentVDomusRequest(naloga_6.ServiceReference1.StudentVDomusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StudentVDomusRequestBody {
        
        public StudentVDomusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentVDomusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentVDomusResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.StudentVDomusResponseBody Body;
        
        public StudentVDomusResponse() {
        }
        
        public StudentVDomusResponse(naloga_6.ServiceReference1.StudentVDomusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentVDomusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.StudentVDomu[] StudentVDomusResult;
        
        public StudentVDomusResponseBody() {
        }
        
        public StudentVDomusResponseBody(naloga_6.ServiceReference1.StudentVDomu[] StudentVDomusResult) {
            this.StudentVDomusResult = StudentVDomusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IzpisNajstarejsegaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IzpisNajstarejsega", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.IzpisNajstarejsegaRequestBody Body;
        
        public IzpisNajstarejsegaRequest() {
        }
        
        public IzpisNajstarejsegaRequest(naloga_6.ServiceReference1.IzpisNajstarejsegaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IzpisNajstarejsegaRequestBody {
        
        public IzpisNajstarejsegaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IzpisNajstarejsegaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IzpisNajstarejsegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.IzpisNajstarejsegaResponseBody Body;
        
        public IzpisNajstarejsegaResponse() {
        }
        
        public IzpisNajstarejsegaResponse(naloga_6.ServiceReference1.IzpisNajstarejsegaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IzpisNajstarejsegaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Student IzpisNajstarejsegaResult;
        
        public IzpisNajstarejsegaResponseBody() {
        }
        
        public IzpisNajstarejsegaResponseBody(naloga_6.ServiceReference1.Student IzpisNajstarejsegaResult) {
            this.IzpisNajstarejsegaResult = IzpisNajstarejsegaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DodajStudentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DodajStudenta", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.DodajStudentaRequestBody Body;
        
        public DodajStudentaRequest() {
        }
        
        public DodajStudentaRequest(naloga_6.ServiceReference1.DodajStudentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DodajStudentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Student student;
        
        public DodajStudentaRequestBody() {
        }
        
        public DodajStudentaRequestBody(naloga_6.ServiceReference1.Student student) {
            this.student = student;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DodajStudentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DodajStudentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.DodajStudentaResponseBody Body;
        
        public DodajStudentaResponse() {
        }
        
        public DodajStudentaResponse(naloga_6.ServiceReference1.DodajStudentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DodajStudentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DodajStudentaResult;
        
        public DodajStudentaResponseBody() {
        }
        
        public DodajStudentaResponseBody(bool DodajStudentaResult) {
            this.DodajStudentaResult = DodajStudentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DodajStudentskiDomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DodajStudentskiDom", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.DodajStudentskiDomRequestBody Body;
        
        public DodajStudentskiDomRequest() {
        }
        
        public DodajStudentskiDomRequest(naloga_6.ServiceReference1.DodajStudentskiDomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DodajStudentskiDomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Studentski_dom dom;
        
        public DodajStudentskiDomRequestBody() {
        }
        
        public DodajStudentskiDomRequestBody(naloga_6.ServiceReference1.Studentski_dom dom) {
            this.dom = dom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DodajStudentskiDomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DodajStudentskiDomResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.DodajStudentskiDomResponseBody Body;
        
        public DodajStudentskiDomResponse() {
        }
        
        public DodajStudentskiDomResponse(naloga_6.ServiceReference1.DodajStudentskiDomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DodajStudentskiDomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DodajStudentskiDomResult;
        
        public DodajStudentskiDomResponseBody() {
        }
        
        public DodajStudentskiDomResponseBody(bool DodajStudentskiDomResult) {
            this.DodajStudentskiDomResult = DodajStudentskiDomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DodajStudentaVDomuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DodajStudentaVDomu", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.DodajStudentaVDomuRequestBody Body;
        
        public DodajStudentaVDomuRequest() {
        }
        
        public DodajStudentaVDomuRequest(naloga_6.ServiceReference1.DodajStudentaVDomuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DodajStudentaVDomuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public naloga_6.ServiceReference1.Student student;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public naloga_6.ServiceReference1.Studentski_dom studentski_dom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int dolzina_bivanja;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tip;
        
        public DodajStudentaVDomuRequestBody() {
        }
        
        public DodajStudentaVDomuRequestBody(naloga_6.ServiceReference1.Student student, naloga_6.ServiceReference1.Studentski_dom studentski_dom, int dolzina_bivanja, string tip) {
            this.student = student;
            this.studentski_dom = studentski_dom;
            this.dolzina_bivanja = dolzina_bivanja;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DodajStudentaVDomuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DodajStudentaVDomuResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.DodajStudentaVDomuResponseBody Body;
        
        public DodajStudentaVDomuResponse() {
        }
        
        public DodajStudentaVDomuResponse(naloga_6.ServiceReference1.DodajStudentaVDomuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DodajStudentaVDomuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DodajStudentaVDomuResult;
        
        public DodajStudentaVDomuResponseBody() {
        }
        
        public DodajStudentaVDomuResponseBody(bool DodajStudentaVDomuResult) {
            this.DodajStudentaVDomuResult = DodajStudentaVDomuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrediStudentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrediStudenta", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.UrediStudentaRequestBody Body;
        
        public UrediStudentaRequest() {
        }
        
        public UrediStudentaRequest(naloga_6.ServiceReference1.UrediStudentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrediStudentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUporabnika;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int emso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Priimek;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int leto_rojstva;
        
        public UrediStudentaRequestBody() {
        }
        
        public UrediStudentaRequestBody(int idUporabnika, int emso, string Ime, string Priimek, int leto_rojstva) {
            this.idUporabnika = idUporabnika;
            this.emso = emso;
            this.Ime = Ime;
            this.Priimek = Priimek;
            this.leto_rojstva = leto_rojstva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrediStudentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrediStudentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.UrediStudentaResponseBody Body;
        
        public UrediStudentaResponse() {
        }
        
        public UrediStudentaResponse(naloga_6.ServiceReference1.UrediStudentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrediStudentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UrediStudentaResult;
        
        public UrediStudentaResponseBody() {
        }
        
        public UrediStudentaResponseBody(bool UrediStudentaResult) {
            this.UrediStudentaResult = UrediStudentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrediDomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrediDom", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.UrediDomRequestBody Body;
        
        public UrediDomRequest() {
        }
        
        public UrediDomRequest(naloga_6.ServiceReference1.UrediDomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrediDomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int stevilkadoma;
        
        public UrediDomRequestBody() {
        }
        
        public UrediDomRequestBody(int Id, string ime, int stevilkadoma) {
            this.Id = Id;
            this.ime = ime;
            this.stevilkadoma = stevilkadoma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrediDomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrediDomResponse", Namespace="http://tempuri.org/", Order=0)]
        public naloga_6.ServiceReference1.UrediDomResponseBody Body;
        
        public UrediDomResponse() {
        }
        
        public UrediDomResponse(naloga_6.ServiceReference1.UrediDomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrediDomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UrediDomResult;
        
        public UrediDomResponseBody() {
        }
        
        public UrediDomResponseBody(bool UrediDomResult) {
            this.UrediDomResult = UrediDomResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StoritveSoapChannel : naloga_6.ServiceReference1.StoritveSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoritveSoapClient : System.ServiceModel.ClientBase<naloga_6.ServiceReference1.StoritveSoap>, naloga_6.ServiceReference1.StoritveSoap {
        
        public StoritveSoapClient() {
        }
        
        public StoritveSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoritveSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoritveSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoritveSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.vpisResponse naloga_6.ServiceReference1.StoritveSoap.vpis(naloga_6.ServiceReference1.vpisRequest request) {
            return base.Channel.vpis(request);
        }
        
        public bool vpis(string uporabniško_ime, string geslo) {
            naloga_6.ServiceReference1.vpisRequest inValue = new naloga_6.ServiceReference1.vpisRequest();
            inValue.Body = new naloga_6.ServiceReference1.vpisRequestBody();
            inValue.Body.uporabniško_ime = uporabniško_ime;
            inValue.Body.geslo = geslo;
            naloga_6.ServiceReference1.vpisResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).vpis(inValue);
            return retVal.Body.vpisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.vpisResponse> naloga_6.ServiceReference1.StoritveSoap.vpisAsync(naloga_6.ServiceReference1.vpisRequest request) {
            return base.Channel.vpisAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.vpisResponse> vpisAsync(string uporabniško_ime, string geslo) {
            naloga_6.ServiceReference1.vpisRequest inValue = new naloga_6.ServiceReference1.vpisRequest();
            inValue.Body = new naloga_6.ServiceReference1.vpisRequestBody();
            inValue.Body.uporabniško_ime = uporabniško_ime;
            inValue.Body.geslo = geslo;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).vpisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.PridobiVseStudenteResponse naloga_6.ServiceReference1.StoritveSoap.PridobiVseStudente(naloga_6.ServiceReference1.PridobiVseStudenteRequest request) {
            return base.Channel.PridobiVseStudente(request);
        }
        
        public naloga_6.ServiceReference1.Student[] PridobiVseStudente() {
            naloga_6.ServiceReference1.PridobiVseStudenteRequest inValue = new naloga_6.ServiceReference1.PridobiVseStudenteRequest();
            inValue.Body = new naloga_6.ServiceReference1.PridobiVseStudenteRequestBody();
            naloga_6.ServiceReference1.PridobiVseStudenteResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).PridobiVseStudente(inValue);
            return retVal.Body.PridobiVseStudenteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseStudenteResponse> naloga_6.ServiceReference1.StoritveSoap.PridobiVseStudenteAsync(naloga_6.ServiceReference1.PridobiVseStudenteRequest request) {
            return base.Channel.PridobiVseStudenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseStudenteResponse> PridobiVseStudenteAsync() {
            naloga_6.ServiceReference1.PridobiVseStudenteRequest inValue = new naloga_6.ServiceReference1.PridobiVseStudenteRequest();
            inValue.Body = new naloga_6.ServiceReference1.PridobiVseStudenteRequestBody();
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).PridobiVseStudenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.PridobiVseDomoveResponse naloga_6.ServiceReference1.StoritveSoap.PridobiVseDomove(naloga_6.ServiceReference1.PridobiVseDomoveRequest request) {
            return base.Channel.PridobiVseDomove(request);
        }
        
        public naloga_6.ServiceReference1.Studentski_dom[] PridobiVseDomove() {
            naloga_6.ServiceReference1.PridobiVseDomoveRequest inValue = new naloga_6.ServiceReference1.PridobiVseDomoveRequest();
            inValue.Body = new naloga_6.ServiceReference1.PridobiVseDomoveRequestBody();
            naloga_6.ServiceReference1.PridobiVseDomoveResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).PridobiVseDomove(inValue);
            return retVal.Body.PridobiVseDomoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseDomoveResponse> naloga_6.ServiceReference1.StoritveSoap.PridobiVseDomoveAsync(naloga_6.ServiceReference1.PridobiVseDomoveRequest request) {
            return base.Channel.PridobiVseDomoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseDomoveResponse> PridobiVseDomoveAsync() {
            naloga_6.ServiceReference1.PridobiVseDomoveRequest inValue = new naloga_6.ServiceReference1.PridobiVseDomoveRequest();
            inValue.Body = new naloga_6.ServiceReference1.PridobiVseDomoveRequestBody();
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).PridobiVseDomoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponse naloga_6.ServiceReference1.StoritveSoap.PridobiVseStudenteVDomu(naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest request) {
            return base.Channel.PridobiVseStudenteVDomu(request);
        }
        
        public naloga_6.ServiceReference1.Student[] PridobiVseStudenteVDomu(int stevilka_doma) {
            naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest inValue = new naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest();
            inValue.Body = new naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequestBody();
            inValue.Body.stevilka_doma = stevilka_doma;
            naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).PridobiVseStudenteVDomu(inValue);
            return retVal.Body.PridobiVseStudenteVDomuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponse> naloga_6.ServiceReference1.StoritveSoap.PridobiVseStudenteVDomuAsync(naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest request) {
            return base.Channel.PridobiVseStudenteVDomuAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.PridobiVseStudenteVDomuResponse> PridobiVseStudenteVDomuAsync(int stevilka_doma) {
            naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest inValue = new naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequest();
            inValue.Body = new naloga_6.ServiceReference1.PridobiVseStudenteVDomuRequestBody();
            inValue.Body.stevilka_doma = stevilka_doma;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).PridobiVseStudenteVDomuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.VrniStudentaResponse naloga_6.ServiceReference1.StoritveSoap.VrniStudenta(naloga_6.ServiceReference1.VrniStudentaRequest request) {
            return base.Channel.VrniStudenta(request);
        }
        
        public naloga_6.ServiceReference1.Student VrniStudenta(int emso) {
            naloga_6.ServiceReference1.VrniStudentaRequest inValue = new naloga_6.ServiceReference1.VrniStudentaRequest();
            inValue.Body = new naloga_6.ServiceReference1.VrniStudentaRequestBody();
            inValue.Body.emso = emso;
            naloga_6.ServiceReference1.VrniStudentaResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).VrniStudenta(inValue);
            return retVal.Body.VrniStudentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.VrniStudentaResponse> naloga_6.ServiceReference1.StoritveSoap.VrniStudentaAsync(naloga_6.ServiceReference1.VrniStudentaRequest request) {
            return base.Channel.VrniStudentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.VrniStudentaResponse> VrniStudentaAsync(int emso) {
            naloga_6.ServiceReference1.VrniStudentaRequest inValue = new naloga_6.ServiceReference1.VrniStudentaRequest();
            inValue.Body = new naloga_6.ServiceReference1.VrniStudentaRequestBody();
            inValue.Body.emso = emso;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).VrniStudentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.VrniDomResponse naloga_6.ServiceReference1.StoritveSoap.VrniDom(naloga_6.ServiceReference1.VrniDomRequest request) {
            return base.Channel.VrniDom(request);
        }
        
        public naloga_6.ServiceReference1.Studentski_dom VrniDom() {
            naloga_6.ServiceReference1.VrniDomRequest inValue = new naloga_6.ServiceReference1.VrniDomRequest();
            inValue.Body = new naloga_6.ServiceReference1.VrniDomRequestBody();
            naloga_6.ServiceReference1.VrniDomResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).VrniDom(inValue);
            return retVal.Body.VrniDomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.VrniDomResponse> naloga_6.ServiceReference1.StoritveSoap.VrniDomAsync(naloga_6.ServiceReference1.VrniDomRequest request) {
            return base.Channel.VrniDomAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.VrniDomResponse> VrniDomAsync() {
            naloga_6.ServiceReference1.VrniDomRequest inValue = new naloga_6.ServiceReference1.VrniDomRequest();
            inValue.Body = new naloga_6.ServiceReference1.VrniDomRequestBody();
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).VrniDomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.StudentVDomusResponse naloga_6.ServiceReference1.StoritveSoap.StudentVDomus(naloga_6.ServiceReference1.StudentVDomusRequest request) {
            return base.Channel.StudentVDomus(request);
        }
        
        public naloga_6.ServiceReference1.StudentVDomu[] StudentVDomus() {
            naloga_6.ServiceReference1.StudentVDomusRequest inValue = new naloga_6.ServiceReference1.StudentVDomusRequest();
            inValue.Body = new naloga_6.ServiceReference1.StudentVDomusRequestBody();
            naloga_6.ServiceReference1.StudentVDomusResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).StudentVDomus(inValue);
            return retVal.Body.StudentVDomusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.StudentVDomusResponse> naloga_6.ServiceReference1.StoritveSoap.StudentVDomusAsync(naloga_6.ServiceReference1.StudentVDomusRequest request) {
            return base.Channel.StudentVDomusAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.StudentVDomusResponse> StudentVDomusAsync() {
            naloga_6.ServiceReference1.StudentVDomusRequest inValue = new naloga_6.ServiceReference1.StudentVDomusRequest();
            inValue.Body = new naloga_6.ServiceReference1.StudentVDomusRequestBody();
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).StudentVDomusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.IzpisNajstarejsegaResponse naloga_6.ServiceReference1.StoritveSoap.IzpisNajstarejsega(naloga_6.ServiceReference1.IzpisNajstarejsegaRequest request) {
            return base.Channel.IzpisNajstarejsega(request);
        }
        
        public naloga_6.ServiceReference1.Student IzpisNajstarejsega() {
            naloga_6.ServiceReference1.IzpisNajstarejsegaRequest inValue = new naloga_6.ServiceReference1.IzpisNajstarejsegaRequest();
            inValue.Body = new naloga_6.ServiceReference1.IzpisNajstarejsegaRequestBody();
            naloga_6.ServiceReference1.IzpisNajstarejsegaResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).IzpisNajstarejsega(inValue);
            return retVal.Body.IzpisNajstarejsegaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.IzpisNajstarejsegaResponse> naloga_6.ServiceReference1.StoritveSoap.IzpisNajstarejsegaAsync(naloga_6.ServiceReference1.IzpisNajstarejsegaRequest request) {
            return base.Channel.IzpisNajstarejsegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.IzpisNajstarejsegaResponse> IzpisNajstarejsegaAsync() {
            naloga_6.ServiceReference1.IzpisNajstarejsegaRequest inValue = new naloga_6.ServiceReference1.IzpisNajstarejsegaRequest();
            inValue.Body = new naloga_6.ServiceReference1.IzpisNajstarejsegaRequestBody();
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).IzpisNajstarejsegaAsync(inValue);
        }
        
        public double IzpisPovprecneStarosti() {
            return base.Channel.IzpisPovprecneStarosti();
        }
        
        public System.Threading.Tasks.Task<double> IzpisPovprecneStarostiAsync() {
            return base.Channel.IzpisPovprecneStarostiAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.DodajStudentaResponse naloga_6.ServiceReference1.StoritveSoap.DodajStudenta(naloga_6.ServiceReference1.DodajStudentaRequest request) {
            return base.Channel.DodajStudenta(request);
        }
        
        public bool DodajStudenta(naloga_6.ServiceReference1.Student student) {
            naloga_6.ServiceReference1.DodajStudentaRequest inValue = new naloga_6.ServiceReference1.DodajStudentaRequest();
            inValue.Body = new naloga_6.ServiceReference1.DodajStudentaRequestBody();
            inValue.Body.student = student;
            naloga_6.ServiceReference1.DodajStudentaResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).DodajStudenta(inValue);
            return retVal.Body.DodajStudentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentaResponse> naloga_6.ServiceReference1.StoritveSoap.DodajStudentaAsync(naloga_6.ServiceReference1.DodajStudentaRequest request) {
            return base.Channel.DodajStudentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentaResponse> DodajStudentaAsync(naloga_6.ServiceReference1.Student student) {
            naloga_6.ServiceReference1.DodajStudentaRequest inValue = new naloga_6.ServiceReference1.DodajStudentaRequest();
            inValue.Body = new naloga_6.ServiceReference1.DodajStudentaRequestBody();
            inValue.Body.student = student;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).DodajStudentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.DodajStudentskiDomResponse naloga_6.ServiceReference1.StoritveSoap.DodajStudentskiDom(naloga_6.ServiceReference1.DodajStudentskiDomRequest request) {
            return base.Channel.DodajStudentskiDom(request);
        }
        
        public bool DodajStudentskiDom(naloga_6.ServiceReference1.Studentski_dom dom) {
            naloga_6.ServiceReference1.DodajStudentskiDomRequest inValue = new naloga_6.ServiceReference1.DodajStudentskiDomRequest();
            inValue.Body = new naloga_6.ServiceReference1.DodajStudentskiDomRequestBody();
            inValue.Body.dom = dom;
            naloga_6.ServiceReference1.DodajStudentskiDomResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).DodajStudentskiDom(inValue);
            return retVal.Body.DodajStudentskiDomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentskiDomResponse> naloga_6.ServiceReference1.StoritveSoap.DodajStudentskiDomAsync(naloga_6.ServiceReference1.DodajStudentskiDomRequest request) {
            return base.Channel.DodajStudentskiDomAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentskiDomResponse> DodajStudentskiDomAsync(naloga_6.ServiceReference1.Studentski_dom dom) {
            naloga_6.ServiceReference1.DodajStudentskiDomRequest inValue = new naloga_6.ServiceReference1.DodajStudentskiDomRequest();
            inValue.Body = new naloga_6.ServiceReference1.DodajStudentskiDomRequestBody();
            inValue.Body.dom = dom;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).DodajStudentskiDomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.DodajStudentaVDomuResponse naloga_6.ServiceReference1.StoritveSoap.DodajStudentaVDomu(naloga_6.ServiceReference1.DodajStudentaVDomuRequest request) {
            return base.Channel.DodajStudentaVDomu(request);
        }
        
        public bool DodajStudentaVDomu(naloga_6.ServiceReference1.Student student, naloga_6.ServiceReference1.Studentski_dom studentski_dom, int dolzina_bivanja, string tip) {
            naloga_6.ServiceReference1.DodajStudentaVDomuRequest inValue = new naloga_6.ServiceReference1.DodajStudentaVDomuRequest();
            inValue.Body = new naloga_6.ServiceReference1.DodajStudentaVDomuRequestBody();
            inValue.Body.student = student;
            inValue.Body.studentski_dom = studentski_dom;
            inValue.Body.dolzina_bivanja = dolzina_bivanja;
            inValue.Body.tip = tip;
            naloga_6.ServiceReference1.DodajStudentaVDomuResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).DodajStudentaVDomu(inValue);
            return retVal.Body.DodajStudentaVDomuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentaVDomuResponse> naloga_6.ServiceReference1.StoritveSoap.DodajStudentaVDomuAsync(naloga_6.ServiceReference1.DodajStudentaVDomuRequest request) {
            return base.Channel.DodajStudentaVDomuAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.DodajStudentaVDomuResponse> DodajStudentaVDomuAsync(naloga_6.ServiceReference1.Student student, naloga_6.ServiceReference1.Studentski_dom studentski_dom, int dolzina_bivanja, string tip) {
            naloga_6.ServiceReference1.DodajStudentaVDomuRequest inValue = new naloga_6.ServiceReference1.DodajStudentaVDomuRequest();
            inValue.Body = new naloga_6.ServiceReference1.DodajStudentaVDomuRequestBody();
            inValue.Body.student = student;
            inValue.Body.studentski_dom = studentski_dom;
            inValue.Body.dolzina_bivanja = dolzina_bivanja;
            inValue.Body.tip = tip;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).DodajStudentaVDomuAsync(inValue);
        }
        
        public bool OdstraniStudenta(int id) {
            return base.Channel.OdstraniStudenta(id);
        }
        
        public System.Threading.Tasks.Task<bool> OdstraniStudentaAsync(int id) {
            return base.Channel.OdstraniStudentaAsync(id);
        }
        
        public bool OdstraniDom(int id) {
            return base.Channel.OdstraniDom(id);
        }
        
        public System.Threading.Tasks.Task<bool> OdstraniDomAsync(int id) {
            return base.Channel.OdstraniDomAsync(id);
        }
        
        public bool OdstraniStudentaizDomov(int id) {
            return base.Channel.OdstraniStudentaizDomov(id);
        }
        
        public System.Threading.Tasks.Task<bool> OdstraniStudentaizDomovAsync(int id) {
            return base.Channel.OdstraniStudentaizDomovAsync(id);
        }
        
        public bool OdstraniDomIzStudentVDomu(int id) {
            return base.Channel.OdstraniDomIzStudentVDomu(id);
        }
        
        public System.Threading.Tasks.Task<bool> OdstraniDomIzStudentVDomuAsync(int id) {
            return base.Channel.OdstraniDomIzStudentVDomuAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.UrediStudentaResponse naloga_6.ServiceReference1.StoritveSoap.UrediStudenta(naloga_6.ServiceReference1.UrediStudentaRequest request) {
            return base.Channel.UrediStudenta(request);
        }
        
        public bool UrediStudenta(int idUporabnika, int emso, string Ime, string Priimek, int leto_rojstva) {
            naloga_6.ServiceReference1.UrediStudentaRequest inValue = new naloga_6.ServiceReference1.UrediStudentaRequest();
            inValue.Body = new naloga_6.ServiceReference1.UrediStudentaRequestBody();
            inValue.Body.idUporabnika = idUporabnika;
            inValue.Body.emso = emso;
            inValue.Body.Ime = Ime;
            inValue.Body.Priimek = Priimek;
            inValue.Body.leto_rojstva = leto_rojstva;
            naloga_6.ServiceReference1.UrediStudentaResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).UrediStudenta(inValue);
            return retVal.Body.UrediStudentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.UrediStudentaResponse> naloga_6.ServiceReference1.StoritveSoap.UrediStudentaAsync(naloga_6.ServiceReference1.UrediStudentaRequest request) {
            return base.Channel.UrediStudentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.UrediStudentaResponse> UrediStudentaAsync(int idUporabnika, int emso, string Ime, string Priimek, int leto_rojstva) {
            naloga_6.ServiceReference1.UrediStudentaRequest inValue = new naloga_6.ServiceReference1.UrediStudentaRequest();
            inValue.Body = new naloga_6.ServiceReference1.UrediStudentaRequestBody();
            inValue.Body.idUporabnika = idUporabnika;
            inValue.Body.emso = emso;
            inValue.Body.Ime = Ime;
            inValue.Body.Priimek = Priimek;
            inValue.Body.leto_rojstva = leto_rojstva;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).UrediStudentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        naloga_6.ServiceReference1.UrediDomResponse naloga_6.ServiceReference1.StoritveSoap.UrediDom(naloga_6.ServiceReference1.UrediDomRequest request) {
            return base.Channel.UrediDom(request);
        }
        
        public bool UrediDom(int Id, string ime, int stevilkadoma) {
            naloga_6.ServiceReference1.UrediDomRequest inValue = new naloga_6.ServiceReference1.UrediDomRequest();
            inValue.Body = new naloga_6.ServiceReference1.UrediDomRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.ime = ime;
            inValue.Body.stevilkadoma = stevilkadoma;
            naloga_6.ServiceReference1.UrediDomResponse retVal = ((naloga_6.ServiceReference1.StoritveSoap)(this)).UrediDom(inValue);
            return retVal.Body.UrediDomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<naloga_6.ServiceReference1.UrediDomResponse> naloga_6.ServiceReference1.StoritveSoap.UrediDomAsync(naloga_6.ServiceReference1.UrediDomRequest request) {
            return base.Channel.UrediDomAsync(request);
        }
        
        public System.Threading.Tasks.Task<naloga_6.ServiceReference1.UrediDomResponse> UrediDomAsync(int Id, string ime, int stevilkadoma) {
            naloga_6.ServiceReference1.UrediDomRequest inValue = new naloga_6.ServiceReference1.UrediDomRequest();
            inValue.Body = new naloga_6.ServiceReference1.UrediDomRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.ime = ime;
            inValue.Body.stevilkadoma = stevilkadoma;
            return ((naloga_6.ServiceReference1.StoritveSoap)(this)).UrediDomAsync(inValue);
        }
    }
}
